CREATE TABLE MonAn (
    IDMA INTEGER PRIMARY KEY AUTOINCREMENT,
    TenMonAn NVARCHAR(70),
    HinhAnh TEXT,
    IDNCC INTEGER,
    FOREIGN KEY (IDNCC) REFERENCES NguoiDung(IDNCC)
)
GO

CREATE TABLE NguoiDung (
    IDNCC INTEGER PRIMARY KEY AUTOINCREMENT,
    HoVaTen NVARCHAR(70),
    QuyenHan VARCHAR(50)
)
GO