CREATE TABLE NguoiDung (
    IDNCC INTEGER PRIMARY KEY AUTOINCREMENT,
    HoVaTen NVARCHAR(100),
    QuyenHan NVARCHAR(50)
);

CREATE TABLE MonAn (
    IDMA INTEGER PRIMARY KEY AUTOINCREMENT, 
    TenMonAn NVARCHAR(100),
    HinhAnh NVARCHAR(255),
    IDNCC INTEGER,
    FOREIGN KEY (IDNCC) REFERENCES NguoiDung(IDNCC)
);

SELECT * FROM MonAn;

SELECT * FROM NguoiDung;

DELETE FROM NguoiDung;

DELETE FROM MonAn;